### ISSUE TITLE
Wrong parsing of rows

### ISSUE THREAD

**Issue by varosi** [ozataman/csv-conduit#27] opened 2017-05-11 12:40 UTC
I have this file:

> hello,","," ",world,"!"
> hello,","," ",world,"!"
> hello,","," ",world,"!"

Parsing it with this program:
```
    s <- BS.readFile input
    let Right csv = decodeCSV (CSVSettings ',' (Just '"')) s :: Either SomeException (Vector (Row BS.ByteString))
    print . Data.Vector.length $ csv
```

Result is "1". Why?

**Comment by MichaelXavier** [comment] 2017-05-19 15:43
Probably duplicate of #24 ?

**Comment by dmvianna** [comment] 2024-10-09 06:32
This issue looks stale, probably solved. If still an issue, feel free to reopen.

**Closed by dmvianna** 2024-10-09 06:32 UTC

**Comment by varosi** [comment] 2024-10-10 04:45
It has to be tested to see if the issue still persists.

**Comment by dmvianna** [comment] 2024-10-10 05:02
If you're willing to do it, I'm happy to help.
